export const HEADER = '/'
export const DASHBOARD = '/'
export const TRANSFER_EVENTS = '/transfer'
export const CREATE_ITEM = '/item/create'
export const ITEM = '/item/detail/:id'
export const ALERTS = '/alerts'
export const PROFILE = '/profile'
