export const HEADER = '/'
export const DASHBOARD = '/'
export const TRANSFER_EVENTS = '/transfer'
export const CREATE_ITEM = '/items/create'
export const ALERTS = '/alerts'
export const PROFILE = '/profile'
